### ISSUE TITLE
Error when setting up new devices using hdmi_cec component

### ISSUE THREAD

**Issue by konikvranik** [konikvranik/home-assistant#2]
Original issue: home-assistant/home-assistant#5727

Make sure you are running the latest version of Home Assistant before reporting an issue.

You should only file an issue if you found a bug. Feature and enhancement requests should go in [the Feature Requests section](https://community.home-assistant.io/c/feature-requests) of our community forum:

**Home Assistant release (`hass --version`):**
3.7.1

**Python release (`python3 --version`):**
3.4.2

**Component/platform:**
hdmi_cec

**Description of problem:**
Upon initialisation of hdmi_cec component, at the stage of discovering devices and creating keys it errors out. Still able to run commands via manual service calls but devices not receiving entity IDs.

**Expected:**
Device receives entity ID

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**
```yaml
hdmi_cec:
  devices:
    TV: 0.0.0.0
    RasPi: 1.0.0.0
    PC: 2.0.0.0
    Fire TV Stick: 3.0.0.0
```

1. install homeassistant in venv on latest raspbian jessie pixel
2. build and install platform and libcec as directed on Pulse 8 repo (specific raspi install instructions) as well as symlink in to venv
3. add hdmI_cec to config

**Traceback (if applicable):**
```bash
Feb  3 00:32:05 HASS hass[698]: ERROR:asyncio:Exception in callback setup.<locals>._new_device(<pycec.networ...at 0x692705b0>) at /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297
Feb  3 00:32:06 HASS hass[698]: handle: <Handle setup.<locals>._new_device(<pycec.networ...at 0x692705b0>) at /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297>
Feb  3 00:32:06 HASS hass[698]: Traceback (most recent call last):
Feb  3 00:32:06 HASS hass[698]: File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
Feb  3 00:32:06 HASS hass[698]: self._callback(*self._args)
Feb  3 00:32:06 HASS hass[698]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py", line 303, in _new_device
Feb  3 00:32:06 HASS hass[698]: CONF_CUSTOMIZE, {}).get(key, {}).get(CONF_PLATFORM, platform),
Feb  3 00:32:06 HASS hass[698]: AttributeError: 'NodeListClass' object has no attribute 'get'
Feb  3 00:32:06 HASS hass[698]: ERROR:asyncio:Exception in callback setup.<locals>._new_device(<pycec.networ...at 0x763ee570>) at /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297
Feb  3 00:32:06 HASS hass[698]: handle: <Handle setup.<locals>._new_device(<pycec.networ...at 0x763ee570>) at /srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297>
Feb  3 00:32:06 HASS hass[698]: Traceback (most recent call last):
Feb  3 00:32:06 HASS hass[698]: File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
Feb  3 00:32:06 HASS hass[698]: self._callback(*self._args)
Feb  3 00:32:06 HASS hass[698]: File "/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py", line 303, in _new_device
Feb  3 00:32:06 HASS hass[698]: CONF_CUSTOMIZE, {}).get(key, {}).get(CONF_PLATFORM, platform),
Feb  3 00:32:06 HASS hass[698]: AttributeError: 'NodeListClass' object has no attribute 'get'
```

**Additional info:**

**Comment by konikvranik** [comment]
Further information, tried reinstalling using HASSbian image, manually compiled libcec, symlinked in to venv, added homeassistant to video group, same error. Is it possible that something has changed since this was all tested? Just to reiterate, can manually do commands to devices from the dash, but in the background the entities aren't being created.

```
17-02-05 23:05:12 ERROR (Thread-18) [asyncio] Exception in callback setup.<locals>._new_device(<pycec.networ...at 0x69198ff0>) at /srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297
handle: <Handle setup.<locals>._new_device(<pycec.networ...at 0x69198ff0>) at /srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py", line 303, in _new_device
    CONF_CUSTOMIZE, {}).get(key, {}).get(CONF_PLATFORM, platform),
AttributeError: 'NodeListClass' object has no attribute 'get'
17-02-05 23:05:15 ERROR (Thread-18) [asyncio] Exception in callback setup.<locals>._new_device(<pycec.networ...at 0x6fcefe50>) at /srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297
handle: <Handle setup.<locals>._new_device(<pycec.networ...at 0x6fcefe50>) at /srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py:297>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/events.py", line 120, in _run
    self._callback(*self._args)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/hdmi_cec.py", line 303, in _new_device
    CONF_CUSTOMIZE, {}).get(key, {}).get(CONF_PLATFORM, platform),
AttributeError: 'NodeListClass' object has no attribute 'get'

```

**Comment by konikvranik** [comment]
Issue found:
hdmi_cec doesn't set up devices correctly when new style customize: is present in your configuration.
removed customize option (as it was only a rename of two sensors) and now all working correctly.

**Comment by konikvranik** [comment]
REsolved by moving customize part into hdmi_cec section
